### ISSUE TITLE
Helm deploy fails

### ISSUE THREAD

**Issue by ysiivan** [apache/openwhisk-deploy-kube#780]
It's not news as there are several similar issues reported already, but here's mine - ```owdev-install-packages-*``` pod(s) error out with 
```
Defaulted container "install-packages" out of: install-packages, wait-for-healthy-invoker (init)
Cloning into 'openwhisk'...
/openwhisk /
Note: checking out '1.0.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 2c621c07 fix start.sh to work on macos (#5019)
/
/openwhisk/ansible/roles/routemgmt/files /
Installing apimgmt package
error: Package update failed: Put https://localhost:31001/api/v1/namespaces/whisk.system/packages/apimgmt?overwrite=true: dial tcp [::1]:31001: getsockopt: connection refused
Failed to deploy routemgmt package; will pause, uninstall, and try again
Deleting routemgmt actions
error: Unable to get action 'routemgmt/getApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/routemgmt/getApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
error: Unable to get action 'routemgmt/createApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/routemgmt/createApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
error: Unable to get action 'routemgmt/deleteApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/routemgmt/deleteApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
Deleting routemgmt package - but only if it exists
error: Unable to get package 'routemgmt': Get https://localhost:31001/api/v1/namespaces/whisk.system/packages/routemgmt: dial tcp [::1]:31001: getsockopt: connection refused
Deleting apimgmt actions
error: Unable to get action 'apimgmt/getApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/apimgmt/getApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
error: Unable to get action 'apimgmt/createApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/apimgmt/createApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
error: Unable to get action 'apimgmt/deleteApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/apimgmt/deleteApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
Deleting apimgmt package - but only if it exists
error: Unable to get package 'apimgmt': Get https://localhost:31001/api/v1/namespaces/whisk.system/packages/apimgmt: dial tcp [::1]:31001: getsockopt: connection refused
Installing apimgmt package
error: Package update failed: Put https://localhost:31001/api/v1/namespaces/whisk.system/packages/apimgmt?overwrite=true: dial tcp [::1]:31001: getsockopt: connection refused
Failed to deploy routemgmt package; will pause, uninstall, and try again
Deleting routemgmt actions
error: Unable to get action 'routemgmt/getApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/routemgmt/getApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
error: Unable to get action 'routemgmt/createApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/routemgmt/createApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
error: Unable to get action 'routemgmt/deleteApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/routemgmt/deleteApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
Deleting routemgmt package - but only if it exists
error: Unable to get package 'routemgmt': Get https://localhost:31001/api/v1/namespaces/whisk.system/packages/routemgmt: dial tcp [::1]:31001: getsockopt: connection refused
Deleting apimgmt actions
error: Unable to get action 'apimgmt/getApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/apimgmt/getApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
error: Unable to get action 'apimgmt/createApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/apimgmt/createApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
error: Unable to get action 'apimgmt/deleteApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/apimgmt/deleteApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
Deleting apimgmt package - but only if it exists
error: Unable to get package 'apimgmt': Get https://localhost:31001/api/v1/namespaces/whisk.system/packages/apimgmt: dial tcp [::1]:31001: getsockopt: connection refused
Installing apimgmt package
error: Package update failed: Put https://localhost:31001/api/v1/namespaces/whisk.system/packages/apimgmt?overwrite=true: dial tcp [::1]:31001: getsockopt: connection refused
Failed to deploy routemgmt package; will pause, uninstall, and try again
Deleting routemgmt actions
error: Unable to get action 'routemgmt/getApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/routemgmt/getApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
error: Unable to get action 'routemgmt/createApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/routemgmt/createApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
error: Unable to get action 'routemgmt/deleteApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/routemgmt/deleteApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
Deleting routemgmt package - but only if it exists
error: Unable to get package 'routemgmt': Get https://localhost:31001/api/v1/namespaces/whisk.system/packages/routemgmt: dial tcp [::1]:31001: getsockopt: connection refused
Deleting apimgmt actions
error: Unable to get action 'apimgmt/getApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/apimgmt/getApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
error: Unable to get action 'apimgmt/createApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/apimgmt/createApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
error: Unable to get action 'apimgmt/deleteApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/apimgmt/deleteApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
Deleting apimgmt package - but only if it exists
error: Unable to get package 'apimgmt': Get https://localhost:31001/api/v1/namespaces/whisk.system/packages/apimgmt: dial tcp [::1]:31001: getsockopt: connection refused
Installing apimgmt package
error: Package update failed: Put https://localhost:31001/api/v1/namespaces/whisk.system/packages/apimgmt?overwrite=true: dial tcp [::1]:31001: getsockopt: connection refused
Failed to deploy routemgmt package; will pause, uninstall, and try again
Deleting routemgmt actions
error: Unable to get action 'routemgmt/getApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/routemgmt/getApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
error: Unable to get action 'routemgmt/createApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/routemgmt/createApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
error: Unable to get action 'routemgmt/deleteApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/routemgmt/deleteApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
Deleting routemgmt package - but only if it exists
error: Unable to get package 'routemgmt': Get https://localhost:31001/api/v1/namespaces/whisk.system/packages/routemgmt: dial tcp [::1]:31001: getsockopt: connection refused
Deleting apimgmt actions
error: Unable to get action 'apimgmt/getApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/apimgmt/getApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
error: Unable to get action 'apimgmt/createApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/apimgmt/createApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
error: Unable to get action 'apimgmt/deleteApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/apimgmt/deleteApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
Deleting apimgmt package - but only if it exists
error: Unable to get package 'apimgmt': Get https://localhost:31001/api/v1/namespaces/whisk.system/packages/apimgmt: dial tcp [::1]:31001: getsockopt: connection refused
Installing apimgmt package
error: Package update failed: Put https://localhost:31001/api/v1/namespaces/whisk.system/packages/apimgmt?overwrite=true: dial tcp [::1]:31001: getsockopt: connection refused
Failed to deploy routemgmt package; will pause, uninstall, and try again
Deleting routemgmt actions
error: Unable to get action 'routemgmt/getApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/routemgmt/getApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
error: Unable to get action 'routemgmt/createApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/routemgmt/createApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
error: Unable to get action 'routemgmt/deleteApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/routemgmt/deleteApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
Deleting routemgmt package - but only if it exists
error: Unable to get package 'routemgmt': Get https://localhost:31001/api/v1/namespaces/whisk.system/packages/routemgmt: dial tcp [::1]:31001: getsockopt: connection refused
Deleting apimgmt actions
error: Unable to get action 'apimgmt/getApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/apimgmt/getApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
error: Unable to get action 'apimgmt/createApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/apimgmt/createApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
error: Unable to get action 'apimgmt/deleteApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/apimgmt/deleteApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
Deleting apimgmt package - but only if it exists
error: Unable to get package 'apimgmt': Get https://localhost:31001/api/v1/namespaces/whisk.system/packages/apimgmt: dial tcp [::1]:31001: getsockopt: connection refused
Installing apimgmt package
error: Package update failed: Put https://localhost:31001/api/v1/namespaces/whisk.system/packages/apimgmt?overwrite=true: dial tcp [::1]:31001: getsockopt: connection refused
Failed to deploy routemgmt package; will pause, uninstall, and try again
Deleting routemgmt actions
error: Unable to get action 'routemgmt/getApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/routemgmt/getApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
error: Unable to get action 'routemgmt/createApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/routemgmt/createApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
error: Unable to get action 'routemgmt/deleteApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/routemgmt/deleteApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
Deleting routemgmt package - but only if it exists
error: Unable to get package 'routemgmt': Get https://localhost:31001/api/v1/namespaces/whisk.system/packages/routemgmt: dial tcp [::1]:31001: getsockopt: connection refused
Deleting apimgmt actions
error: Unable to get action 'apimgmt/getApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/apimgmt/getApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
error: Unable to get action 'apimgmt/createApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/apimgmt/createApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
error: Unable to get action 'apimgmt/deleteApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/apimgmt/deleteApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
Deleting apimgmt package - but only if it exists
error: Unable to get package 'apimgmt': Get https://localhost:31001/api/v1/namespaces/whisk.system/packages/apimgmt: dial tcp [::1]:31001: getsockopt: connection refused
Installing apimgmt package
error: Package update failed: Put https://localhost:31001/api/v1/namespaces/whisk.system/packages/apimgmt?overwrite=true: dial tcp [::1]:31001: getsockopt: connection refused
Failed to deploy routemgmt package; will pause, uninstall, and try again
Deleting routemgmt actions
error: Unable to get action 'routemgmt/getApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/routemgmt/getApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
error: Unable to get action 'routemgmt/createApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/routemgmt/createApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
error: Unable to get action 'routemgmt/deleteApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/routemgmt/deleteApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
Deleting routemgmt package - but only if it exists
error: Unable to get package 'routemgmt': Get https://localhost:31001/api/v1/namespaces/whisk.system/packages/routemgmt: dial tcp [::1]:31001: getsockopt: connection refused
Deleting apimgmt actions
error: Unable to get action 'apimgmt/getApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/apimgmt/getApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
error: Unable to get action 'apimgmt/createApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/apimgmt/createApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
error: Unable to get action 'apimgmt/deleteApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/apimgmt/deleteApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
Deleting apimgmt package - but only if it exists
error: Unable to get package 'apimgmt': Get https://localhost:31001/api/v1/namespaces/whisk.system/packages/apimgmt: dial tcp [::1]:31001: getsockopt: connection refused
Installing apimgmt package
error: Package update failed: Put https://localhost:31001/api/v1/namespaces/whisk.system/packages/apimgmt?overwrite=true: dial tcp [::1]:31001: getsockopt: connection refused
Failed to deploy routemgmt package; will pause, uninstall, and try again
Deleting routemgmt actions
error: Unable to get action 'routemgmt/getApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/routemgmt/getApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
error: Unable to get action 'routemgmt/createApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/routemgmt/createApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
error: Unable to get action 'routemgmt/deleteApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/routemgmt/deleteApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
Deleting routemgmt package - but only if it exists
error: Unable to get package 'routemgmt': Get https://localhost:31001/api/v1/namespaces/whisk.system/packages/routemgmt: dial tcp [::1]:31001: getsockopt: connection refused
Deleting apimgmt actions
error: Unable to get action 'apimgmt/getApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/apimgmt/getApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
error: Unable to get action 'apimgmt/createApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/apimgmt/createApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
error: Unable to get action 'apimgmt/deleteApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/apimgmt/deleteApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
Deleting apimgmt package - but only if it exists
error: Unable to get package 'apimgmt': Get https://localhost:31001/api/v1/namespaces/whisk.system/packages/apimgmt: dial tcp [::1]:31001: getsockopt: connection refused
Installing apimgmt package
error: Package update failed: Put https://localhost:31001/api/v1/namespaces/whisk.system/packages/apimgmt?overwrite=true: dial tcp [::1]:31001: getsockopt: connection refused
Failed to deploy routemgmt package; will pause, uninstall, and try again
Deleting routemgmt actions
error: Unable to get action 'routemgmt/getApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/routemgmt/getApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
error: Unable to get action 'routemgmt/createApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/routemgmt/createApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
error: Unable to get action 'routemgmt/deleteApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/routemgmt/deleteApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
Deleting routemgmt package - but only if it exists
error: Unable to get package 'routemgmt': Get https://localhost:31001/api/v1/namespaces/whisk.system/packages/routemgmt: dial tcp [::1]:31001: getsockopt: connection refused
Deleting apimgmt actions
error: Unable to get action 'apimgmt/getApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/apimgmt/getApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
error: Unable to get action 'apimgmt/createApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/apimgmt/createApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
error: Unable to get action 'apimgmt/deleteApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/apimgmt/deleteApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
Deleting apimgmt package - but only if it exists
error: Unable to get package 'apimgmt': Get https://localhost:31001/api/v1/namespaces/whisk.system/packages/apimgmt: dial tcp [::1]:31001: getsockopt: connection refused
Installing apimgmt package
error: Package update failed: Put https://localhost:31001/api/v1/namespaces/whisk.system/packages/apimgmt?overwrite=true: dial tcp [::1]:31001: getsockopt: connection refused
Failed to deploy routemgmt package; will pause, uninstall, and try again
Deleting routemgmt actions
error: Unable to get action 'routemgmt/getApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/routemgmt/getApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
error: Unable to get action 'routemgmt/createApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/routemgmt/createApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
error: Unable to get action 'routemgmt/deleteApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/routemgmt/deleteApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
Deleting routemgmt package - but only if it exists
error: Unable to get package 'routemgmt': Get https://localhost:31001/api/v1/namespaces/whisk.system/packages/routemgmt: dial tcp [::1]:31001: getsockopt: connection refused
Deleting apimgmt actions
error: Unable to get action 'apimgmt/getApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/apimgmt/getApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
error: Unable to get action 'apimgmt/createApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/apimgmt/createApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
error: Unable to get action 'apimgmt/deleteApi': Get https://localhost:31001/api/v1/namespaces/whisk.system/actions/apimgmt/deleteApi?code=false: dial tcp [::1]:31001: getsockopt: connection refused
Run 'wsk --help' for usage.
Deleting apimgmt package - but only if it exists
error: Unable to get package 'apimgmt': Get https://localhost:31001/api/v1/namespaces/whisk.system/packages/apimgmt: dial tcp [::1]:31001: getsockopt: connection refused
Giving up after 10 failed attempts to install the routemgmt package
```

**Comment by kcexn** [comment]
Yes, I believe I am having the same issue. Do you also get this following error when you check your debug log at: `/openwhisk/core/routemgmt/getApi/npm-debug.log`?

```bash
1722 verbose cwd /openwhisk/core/routemgmt/getApi
1723 error Linux 6.1.0-37-cloud-amd64
1724 error argv "/usr/bin/node" "/usr/bin/npm" "install"
1725 error node v8.10.0
1726 error npm  v3.5.2
1727 error code EMISSINGARG
1728 error typeerror Error: Missing required argument #1
1728 error typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
1728 error typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
1728 error typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
1728 error typeerror     at /usr/share/npm/lib/install/deps.js:457:7
1728 error typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
1728 error typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
1728 error typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
1728 error typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
1728 error typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
1728 error typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
1729 error typeerror This is an error with npm itself. Please report this error at:
1729 error typeerror     <http://github.com/npm/npm/issues>
1730 verbose exit [ 1, true ]
```

**Comment by kcexn** [comment]
This issue seems to be resolved if you clone this repository and then deploy using the charts from within the repo rather than deploy from the charts distributed in the release, which are quite old.
